### ISSUE TITLE
Error: [hypixel-api-reborn] Invalid API Key

### ISSUE THREAD

**Issue by Samsonite8265** [Solar-Tweaks/SolarStats#22]
C:\Users\samsc\SolarStats>npm start
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> solarstats@1.0.0-dev start
> node .

   _____       _               _____ _        _
  / ____|     | |             / ____| |      | |
 | (___   ___ | | __ _ _ __  | (___ | |_ __ _| |_ ___
  \___ \ / _ \| |/ _` | '__|  \___ \| __/ _` | __/ __|
  ____) | (_) | | (_| | |     ____) | || (_| | |_\__ \
 |_____/ \___/|_|\__,_|_|    |_____/ \__\__,_|\__|___/
                                           v1.0.0-dev

 INFO  Checking for updates...
 INFO  Proxy started
C:\Users\samsc\SolarStats\node_modules\hypixel-api-reborn\src\Private\requests.js:24
    if (res.status === 403) throw new Error(Errors.INVALID_API_KEY);
                                  ^

Error: [hypixel-api-reborn] Invalid API Key! For help join our Discord Server https://discord.gg/NSEBNMM
    at Requests.request (C:\Users\samsc\SolarStats\node_modules\hypixel-api-reborn\src\Private\requests.js:24:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Client._makeRequest (C:\Users\samsc\SolarStats\node_modules\hypixel-api-reborn\src\Client.js:70:20)
    at async Object.module.exports (C:\Users\samsc\SolarStats\node_modules\hypixel-api-reborn\src\API\getKeyInfo.js:4:15)

**Comment by RatchanonDev** [comment]
Did you put your Hypixel API Key in? Go on normal hypixel and do /api new and copy that and put it into your config,
