### ISSUE TITLE
npm run build Error

### ISSUE THREAD

**Issue by MinoaBaccus** [Solar-Tweaks/SolarStats#42]
Full PowerShell Log

```
PS C:\Users\Minoa> git clone https://github.com/Solar-Tweaks/SolarStats
Cloning into 'SolarStats'...
remote: Enumerating objects: 762, done.
remote: Counting objects: 100% (184/184), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 762 (delta 151), reused 119 (delta 117), pack-reused 578
Receiving objects: 100% (762/762), 294.99 KiB | 2.06 MiB/s, done.
Resolving deltas: 100% (483/483), done.
PS C:\Users\Minoa> cd SolarStats
PS C:\Users\Minoa\SolarStats> npm install
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@minecraft-js/lunarbukkitapi@1.1.3',
npm WARN EBADENGINE   required: { node: '>=18.x' },
npm WARN EBADENGINE   current: { node: 'v16.16.0', npm: '8.11.0' }
npm WARN EBADENGINE }

added 382 packages, and audited 383 packages in 9s

65 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\Minoa\SolarStats> npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> solarstats@1.0.0-dev build
> npm run clean && node ./scripts/build.js

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> solarstats@1.0.0-dev clean
> node ./scripts/clean.js

info: cleaning build folder... 🏗️
C:\Users\Minoa\SolarStats\scripts\clean.js:5
  if (!error.message.includes('ENOENT')) throw error;
                                         ^

TypeError: fs.rmSync is not a function
    at Object.<anonymous> (C:\Users\Minoa\SolarStats\scripts\clean.js:10:6)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
PS C:\Users\Minoa\SolarStats>
```

**Comment by TBHGodPro** [comment]
could you go to the solarstats folder, go to the scripts subfolder, open the `clean.js` file and send the code inside it?

**Comment by MinoaBaccus** [comment]
> could you go to the solarstats folder, go to the scripts subfolder, open the `clean.js` file and send the code inside it?

```
const fs = require('fs');
const { join } = require('path');

function handleENOENT(error) {
  if (!error.message.includes('ENOENT')) throw error;
}

try {
  console.log('info: cleaning build folder... 🏗️');
  fs.rmSync(join(__dirname, '..', 'build'), { recursive: true });
} catch (error) {
  handleENOENT(error);
}

try {
  console.log('info: cleaning dist folder... 🚚️');
  fs.rmSync(join(__dirname, '..', 'dist', 'solarstats.exe'));
} catch (error) {
  handleENOENT(error);
}

console.log('info: clean complete! 🗑️\n');

```

**Comment by TBHGodPro** [comment]
Alright try putting this as the `clean.js` code and running.

```javascript
const fs = require('fs');
const { join } = require('path');

console.log(fs, fs.rmSync);

function handleENOENT(error) {
  if (!error.message.includes('ENOENT')) throw error;
}

try {
  console.log('info: cleaning build folder... 🏗️');
  fs.rmSync(join(__dirname, '..', 'build'), { recursive: true });
} catch (error) {
  handleENOENT(error);
}

try {
  console.log('info: cleaning dist folder... 🚚️');
  fs.rmSync(join(__dirname, '..', 'dist', 'solarstats.exe'));
} catch (error) {
  handleENOENT(error);
}

console.log('info: clean complete! 🗑️\n');
```

Then send the console results here

**Comment by MinoaBaccus** [comment]
> Alright try putting this as the `clean.js` code and running.
> 
> ```js
> const fs = require('fs');
> const { join } = require('path');
> 
> console.log(fs, fs.rmSync);
> 
> function handleENOENT(error) {
>   if (!error.message.includes('ENOENT')) throw error;
> }
> 
> try {
>   console.log('info: cleaning build folder... 🏗️');
>   fs.rmSync(join(__dirname, '..', 'build'), { recursive: true });
> } catch (error) {
>   handleENOENT(error);
> }
> 
> try {
>   console.log('info: cleaning dist folder... 🚚️');
>   fs.rmSync(join(__dirname, '..', 'dist', 'solarstats.exe'));
> } catch (error) {
>   handleENOENT(error);
> }
> 
> console.log('info: clean complete! 🗑️\n');
> ```
> 
> Then send the console results here

PS C:\Users\Minoa\desktop\SolarStats> npm run build

> solarstats@1.0.0-dev build
> npm run clean && node ./scripts/build.js


> solarstats@1.0.0-dev clean
> node ./scripts/clean.js

```
{ constants:
   { O_RDONLY: 0,
     O_WRONLY: 1,
     O_RDWR: 2,
     S_IFMT: 61440,
     S_IFREG: 32768,
     S_IFDIR: 16384,
     S_IFCHR: 8192,
     S_IFLNK: 40960,
     O_CREAT: 256,
     O_EXCL: 1024,
     O_TRUNC: 512,
     O_APPEND: 8,
     F_OK: 0,
     R_OK: 4,
     W_OK: 2,
     X_OK: 1 },
  Stats: [Function: Stats],
  F_OK: 0,
  R_OK: 4,
  W_OK: 2,
  X_OK: 1,
  access: [Function],
  accessSync: [Function],
  exists: [Function],
  existsSync: [Function],
  readFile: [Function],
  readFileSync: [Function],
  close: [Function],
  closeSync: [Function],
  open: [Function],
  openSync: [Function],
  read: [Function],
  readSync: [Function],
  write: [Function],
  writeSync: [Function],
  rename: [Function],
  renameSync: [Function],
  truncate: [Function],
  truncateSync: [Function],
  ftruncate: [Function],
  ftruncateSync: [Function],
  rmdir: [Function],
  rmdirSync: [Function],
  fdatasync: [Function],
  fdatasyncSync: [Function],
  fsync: [Function],
  fsyncSync: [Function],
  mkdir: [Function],
  mkdirSync: [Function],
  readdir: [Function],
  readdirSync: [Function],
  fstat: [Function],
  lstat: [Function],
  stat: [Function],
  fstatSync: [Function],
  lstatSync: [Function],
  statSync: [Function],
  readlink: [Function],
  readlinkSync: [Function],
  symlink: [Function],
  symlinkSync: [Function],
  link: [Function],
  linkSync: [Function],
  unlink: [Function],
  unlinkSync: [Function],
  fchmod: [Function],
  fchmodSync: [Function],
  chmod: [Function],
  chmodSync: [Function],
  fchown: [Function],
  fchownSync: [Function],
  chown: [Function],
  chownSync: [Function],
  _toUnixTimestamp: [Function: toUnixTimestamp],
  utimes: [Function],
  utimesSync: [Function],
  futimes: [Function],
  futimesSync: [Function],
  writeFile: [Function],
  writeFileSync: [Function],
  appendFile: [Function],
  appendFileSync: [Function],
  watch: [Function],
  watchFile: [Function],
  unwatchFile: [Function],
  realpathSync: [Function: realpathSync],
  realpath: [Function: realpath],
  mkdtemp: [Function],
  mkdtempSync: [Function],
  createReadStream: [Function],
  ReadStream:
   { [Function: ReadStream]
     super_:
      { [Function: Readable]
        ReadableState: [Function: ReadableState],
        super_: [Object],
        _fromList: [Function: fromList] } },
  FileReadStream:
     super_:
      { [Function: Readable]
        ReadableState: [Function: ReadableState],
        super_: [Object],
        _fromList: [Function: fromList] } },
  createWriteStream: [Function],
  WriteStream:
   { [Function: WriteStream]
     super_: { [Function: Writable] WritableState: [Function: WritableState], super_: [Object] } },
  FileWriteStream:
   { [Function: WriteStream]
     super_: { [Function: Writable] WritableState: [Function: WritableState], super_: [Object] } } } undefined
info: cleaning build folder... 🏗️
C:\Users\Minoa\desktop\SolarStats\scripts\clean.js:7
  if (!error.message.includes('ENOENT')) throw error;
                                         ^

TypeError: fs.rmSync is not a function
    at Object.<anonymous> (C:\Users\Minoa\desktop\SolarStats\scripts\clean.js:12:6)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
PS C:\Users\Minoa\desktop\SolarStats> npm run build

> solarstats@1.0.0-dev build
> npm run clean && node ./scripts/build.js


> solarstats@1.0.0-dev clean
> node ./scripts/clean.js

{ constants:
   { O_RDONLY: 0,
     O_WRONLY: 1,
     O_RDWR: 2,
     S_IFMT: 61440,
     S_IFREG: 32768,
     S_IFDIR: 16384,
     S_IFCHR: 8192,
     S_IFLNK: 40960,
     O_CREAT: 256,
     O_EXCL: 1024,
     O_TRUNC: 512,
     O_APPEND: 8,
     F_OK: 0,
     R_OK: 4,
     W_OK: 2,
     X_OK: 1 },
  Stats: [Function: Stats],
  F_OK: 0,
  R_OK: 4,
  W_OK: 2,
  X_OK: 1,
  access: [Function],
  accessSync: [Function],
  exists: [Function],
  existsSync: [Function],
  readFile: [Function],
  readFileSync: [Function],
  close: [Function],
  closeSync: [Function],
  open: [Function],
  openSync: [Function],
  read: [Function],
  readSync: [Function],
  write: [Function],
  writeSync: [Function],
  rename: [Function],
  renameSync: [Function],
  truncate: [Function],
  truncateSync: [Function],
  ftruncate: [Function],
  ftruncateSync: [Function],
  rmdir: [Function],
  rmdirSync: [Function],
  fdatasync: [Function],
  fdatasyncSync: [Function],
  fsync: [Function],
  fsyncSync: [Function],
  mkdir: [Function],
  mkdirSync: [Function],
  readdir: [Function],
  readdirSync: [Function],
  fstat: [Function],
  lstat: [Function],
  stat: [Function],
  fstatSync: [Function],
  lstatSync: [Function],
  statSync: [Function],
  readlink: [Function],
  readlinkSync: [Function],
  symlink: [Function],
  symlinkSync: [Function],
  link: [Function],
  linkSync: [Function],
  unlink: [Function],
  unlinkSync: [Function],
  fchmod: [Function],
  fchmodSync: [Function],
  chmod: [Function],
  chmodSync: [Function],
  fchown: [Function],
  fchownSync: [Function],
  chown: [Function],
  chownSync: [Function],
  _toUnixTimestamp: [Function: toUnixTimestamp],
  utimes: [Function],
  utimesSync: [Function],
  futimes: [Function],
  futimesSync: [Function],
  writeFile: [Function],
  writeFileSync: [Function],
  appendFile: [Function],
  appendFileSync: [Function],
  watch: [Function],
  watchFile: [Function],
  unwatchFile: [Function],
  realpathSync: [Function: realpathSync],
  realpath: [Function: realpath],
  mkdtemp: [Function],
  mkdtempSync: [Function],
  createReadStream: [Function],
  ReadStream:
   { [Function: ReadStream]
     super_:
      { [Function: Readable]
        ReadableState: [Function: ReadableState],
        super_: [Object],
        _fromList: [Function: fromList] } },
  FileReadStream:
   { [Function: ReadStream]
     super_:
      { [Function: Readable]
        ReadableState: [Function: ReadableState],
        super_: [Object],
        _fromList: [Function: fromList] } },
  createWriteStream: [Function],
  WriteStream:
   { [Function: WriteStream]
     super_: { [Function: Writable] WritableState: [Function: WritableState], super_: [Object] } },
  FileWriteStream:
   { [Function: WriteStream]
     super_: { [Function: Writable] WritableState: [Function: WritableState], super_: [Object] } } } undefined
info: cleaning build folder... 🏗️
C:\Users\Minoa\desktop\SolarStats\scripts\clean.js:7
  if (!error.message.includes('ENOENT')) throw error;
                                         ^

TypeError: fs.rmSync is not a function
    at Object.<anonymous> (C:\Users\Minoa\desktop\SolarStats\scripts\clean.js:12:6)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
```

**Comment by MinoaBaccus** [comment]
> Alright try putting this as the `clean.js` code and running.
> 
> ```js
> const fs = require('fs');
> const { join } = require('path');
> 
> console.log(fs, fs.rmSync);
> 
> function handleENOENT(error) {
>   if (!error.message.includes('ENOENT')) throw error;
> }
> 
> try {
>   console.log('info: cleaning build folder... 🏗️');
>   fs.rmSync(join(__dirname, '..', 'build'), { recursive: true });
> } catch (error) {
>   handleENOENT(error);
> }
> 
> try {
>   console.log('info: cleaning dist folder... 🚚️');
>   fs.rmSync(join(__dirname, '..', 'dist', 'solarstats.exe'));
> } catch (error) {
>   handleENOENT(error);
> }
> 
> console.log('info: clean complete! 🗑️\n');
> ```
> 
> Then send the console results here

`PS C:\Users\Minoa\desktop\SolarStats> npm run build

> solarstats@1.0.0-dev build
> npm run clean && node ./scripts/build.js


> solarstats@1.0.0-dev clean
> node ./scripts/clean.js

{ constants:
   { O_RDONLY: 0,
     O_WRONLY: 1,
     O_RDWR: 2,
     S_IFMT: 61440,
     S_IFREG: 32768,
     S_IFDIR: 16384,
     S_IFCHR: 8192,
     S_IFLNK: 40960,
     O_CREAT: 256,
     O_EXCL: 1024,
     O_TRUNC: 512,
     O_APPEND: 8,
     F_OK: 0,
     R_OK: 4,
     W_OK: 2,
     X_OK: 1 },
  Stats: [Function: Stats],
  F_OK: 0,
  R_OK: 4,
  W_OK: 2,
  X_OK: 1,
  access: [Function],
  accessSync: [Function],
  exists: [Function],
  existsSync: [Function],
  readFile: [Function],
  readFileSync: [Function],
  close: [Function],
  closeSync: [Function],
  open: [Function],
  openSync: [Function],
  read: [Function],
  readSync: [Function],
  write: [Function],
  writeSync: [Function],
  rename: [Function],
  renameSync: [Function],
  truncate: [Function],
  truncateSync: [Function],
  ftruncate: [Function],
  ftruncateSync: [Function],
  rmdir: [Function],
  rmdirSync: [Function],
  fdatasync: [Function],
  fdatasyncSync: [Function],
  fsync: [Function],
  fsyncSync: [Function],
  mkdir: [Function],
  mkdirSync: [Function],
  readdir: [Function],
  readdirSync: [Function],
  fstat: [Function],
  lstat: [Function],
  stat: [Function],
  fstatSync: [Function],
  lstatSync: [Function],
  statSync: [Function],
  readlink: [Function],
  readlinkSync: [Function],
  symlink: [Function],
  symlinkSync: [Function],
  link: [Function],
  linkSync: [Function],
  unlink: [Function],
  unlinkSync: [Function],
  fchmod: [Function],
  fchmodSync: [Function],
  chmod: [Function],
  chmodSync: [Function],
  fchown: [Function],
  fchownSync: [Function],
  chown: [Function],
  chownSync: [Function],
  _toUnixTimestamp: [Function: toUnixTimestamp],
  utimes: [Function],
  utimesSync: [Function],
  futimes: [Function],
  futimesSync: [Function],
  writeFile: [Function],
  writeFileSync: [Function],
  appendFile: [Function],
  appendFileSync: [Function],
  watch: [Function],
  watchFile: [Function],
  unwatchFile: [Function],
  realpathSync: [Function: realpathSync],
  realpath: [Function: realpath],
  mkdtemp: [Function],
  mkdtempSync: [Function],
  createReadStream: [Function],
  ReadStream:
   { [Function: ReadStream]
     super_:
      { [Function: Readable]
        ReadableState: [Function: ReadableState],
        super_: [Object],
        _fromList: [Function: fromList] } },
  FileReadStream:
   { [Function: ReadStream]
     super_:
      { [Function: Readable]
        ReadableState: [Function: ReadableState],
        super_: [Object],
        _fromList: [Function: fromList] } },
  createWriteStream: [Function],
  WriteStream:
   { [Function: WriteStream]
     super_: { [Function: Writable] WritableState: [Function: WritableState], super_: [Object] } },
  FileWriteStream:
   { [Function: WriteStream]
     super_: { [Function: Writable] WritableState: [Function: WritableState], super_: [Object] } } } undefined
info: cleaning build folder... 🏗️
C:\Users\Minoa\desktop\SolarStats\scripts\clean.js:7
  if (!error.message.includes('ENOENT')) throw error;
                                         ^

TypeError: fs.rmSync is not a function
    at Object.<anonymous> (C:\Users\Minoa\desktop\SolarStats\scripts\clean.js:12:6)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3
PS C:\Users\Minoa\desktop\SolarStats>`

**Comment by TBHGodPro** [comment]
alright try running `npm update; npm ci`

**Comment by MinoaBaccus** [comment]
> alright try running `npm update; npm ci`

Now what?

**Comment by TBHGodPro** [comment]
bro what

try deleting the `node_modules` folder, and then run `npm install; npm run build`

**Comment by MinoaBaccus** [comment]
> bro what
> 
> try deleting the `node_modules` folder, and then run `npm install; npm run build`

```
C:\Users\Minoa\Desktop\SolarStats>npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@minecraft-js/lunarbukkitapi@1.2.0',
npm WARN EBADENGINE   required: { node: '>=18.x' },
npm WARN EBADENGINE   current: { node: 'v16.17.0', npm: '8.15.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@minecraft-js/uuid@1.0.3',
npm WARN EBADENGINE   required: { node: '>=18.x' },
npm WARN EBADENGINE   current: { node: 'v16.17.0', npm: '8.15.0' }
npm WARN EBADENGINE }

added 381 packages, and audited 382 packages in 9s

65 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\Minoa\Desktop\SolarStats>npm run build

> solarstats@1.0.0-dev build
> npm run clean && node ./scripts/build.js


> solarstats@1.0.0-dev clean
> node ./scripts/clean.js

{ constants:
   { O_RDONLY: 0,
     O_WRONLY: 1,
     O_RDWR: 2,
     S_IFMT: 61440,
     S_IFREG: 32768,
     S_IFDIR: 16384,
     S_IFCHR: 8192,
     S_IFLNK: 40960,
     O_CREAT: 256,
     O_EXCL: 1024,
     O_TRUNC: 512,
     O_APPEND: 8,
     F_OK: 0,
     R_OK: 4,
     W_OK: 2,
     X_OK: 1 },
  Stats: [Function: Stats],
  F_OK: 0,
  R_OK: 4,
  W_OK: 2,
  X_OK: 1,
  access: [Function],
  accessSync: [Function],
  exists: [Function],
  existsSync: [Function],
  readFile: [Function],
  readFileSync: [Function],
  close: [Function],
  closeSync: [Function],
  open: [Function],
  openSync: [Function],
  read: [Function],
  readSync: [Function],
  write: [Function],
  writeSync: [Function],
  rename: [Function],
  renameSync: [Function],
  truncate: [Function],
  truncateSync: [Function],
  ftruncate: [Function],
  ftruncateSync: [Function],
  rmdir: [Function],
  rmdirSync: [Function],
  fdatasync: [Function],
  fdatasyncSync: [Function],
  fsync: [Function],
  fsyncSync: [Function],
  mkdir: [Function],
  mkdirSync: [Function],
  readdir: [Function],
  readdirSync: [Function],
  fstat: [Function],
  lstat: [Function],
  stat: [Function],
  fstatSync: [Function],
  lstatSync: [Function],
  statSync: [Function],
  readlink: [Function],
  readlinkSync: [Function],
  symlink: [Function],
  symlinkSync: [Function],
  link: [Function],
  linkSync: [Function],
  unlink: [Function],
  unlinkSync: [Function],
  fchmod: [Function],
  fchmodSync: [Function],
  chmod: [Function],
  chmodSync: [Function],
  fchown: [Function],
  fchownSync: [Function],
  chown: [Function],
  chownSync: [Function],
  _toUnixTimestamp: [Function: toUnixTimestamp],
  utimes: [Function],
  utimesSync: [Function],
  futimes: [Function],
  futimesSync: [Function],
  writeFile: [Function],
  writeFileSync: [Function],
  appendFile: [Function],
  appendFileSync: [Function],
  watch: [Function],
  watchFile: [Function],
  unwatchFile: [Function],
  realpathSync: [Function: realpathSync],
  realpath: [Function: realpath],
  mkdtemp: [Function],
  mkdtempSync: [Function],
  createReadStream: [Function],
  ReadStream:
   { [Function: ReadStream]
     super_:
      { [Function: Readable]
        ReadableState: [Function: ReadableState],
        super_: [Object],
        _fromList: [Function: fromList] } },
  FileReadStream:
   { [Function: ReadStream]
     super_:
      { [Function: Readable]
        ReadableState: [Function: ReadableState],
        super_: [Object],
        _fromList: [Function: fromList] } },
  createWriteStream: [Function],
  WriteStream:
   { [Function: WriteStream]
     super_: { [Function: Writable] WritableState: [Function: WritableState], super_: [Object] } },
  FileWriteStream:
   { [Function: WriteStream]
     super_: { [Function: Writable] WritableState: [Function: WritableState], super_: [Object] } } } undefined
info: cleaning build folder... 🏗️
C:\Users\Minoa\Desktop\SolarStats\scripts\clean.js:7
  if (!error.message.includes('ENOENT')) throw error;
                                         ^

TypeError: fs.rmSync is not a function
    at Object.<anonymous> (C:\Users\Minoa\Desktop\SolarStats\scripts\clean.js:12:6)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:500:3

```
